development:
  web_host: http://localhost:3000
  email:
    delivery_method: smtp
    server: smtp.yourdomain.com
    port: 25
    domain: yourdomain.com
    authentication: none
    username:
    password: 
    site_admin_email: admin@yourdomain.com
production:
  web_host: http://localhost:3000  
  email:
    delivery_method: sendmail
    site_admin_email: admin@yourdomain.com
test:
  web_host: http://localhost:3000
  email:
    delivery_method: test
    site_admin_email: admin@yourdomain.com